name: contentpagecmmapp
description: "CMM App Learning Project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.1

  chewie: ^1.7.4
  flutter_svg: ^2.0.9
  get: ^4.6.6
  shared_preferences: ^2.2.2

  cupertino_icons: ^1.0.8

  url_launcher: ^6.2.1

  font_awesome_flutter: ^10.7.0
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6


  youtube_player_flutter: ^9.1.1

  youtube_player_iframe: ^5.2.1

  webview_flutter: ^4.2.2

  flutter_inappwebview: ^6.0.0-beta.22
  firebase_auth: ^5.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # ✅ เพิ่มส่วนนี้เพื่อให้โหลดรูปภาพจากโฟลเดอร์ assets
  assets:
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf


